---
title: "2024_Manuscript"
output: pdf_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stargazer)
library(AER)
library(ggplot2)
library(plm)
library(dplyr)
library(tidyverse)
library(qte)
library(readxl)
library(randomForest)
library(gbm) 
library(MatchIt)
library(plotly)
library(quantreg)
library(mgcv) 
```




```{r}
#Producing Log of Price by Treatment graphics.off
# 1 Kilometer Control

DID1k <- read_excel("data/DTC_DID1k.xlsx",sheet = "Multifam 00-23")
DID1k <- DID1k[,1:25]
DID1k <- DID1k[DID1k$SalePrice < 2500000 & DID1k$SalePrice >= 1, ]
DID1k$FinishArea[DID1k$FinishArea == 0] <- 449
DID1k$LnSalePrice <- log(DID1k$SalePrice + 1)
DID1k$PricePerSqrft <- (DID1k$SalePrice/(DID1k$FinishArea))
DID1k$LnPricePerSqrft <- log(DID1k$SalePrice/(DID1k$FinishArea))
DID1k <- DID1k[!is.na(DID1k$CoreBin) & !is.na(DID1k$Age) & !is.na(DID1k$FinishArea) & !is.na(DID1k$LnSalePrice) &  !is.na(DID1k$SalePrice),]

DID1k_avg <- DID1k %>%
  group_by(Year, CoreBin) %>%
  summarize(mean_LnSalePrice = mean(LnSalePrice, na.rm = TRUE))

# Plot the summarized data
DID1k_avg %>%
 ggplot(aes(x = Year, y = mean_LnSalePrice, group = CoreBin, color = as.factor(CoreBin))) +
  geom_line(linewidth = 1) +
  scale_y_continuous(limits = c(10, 15)) +
  scale_x_discrete("Year",labels=c("2000","", "", "", "" ,"2005", "", "" ,"", "", "2010", "" ,"", "" ,"" ,"2015" ,"" ,"" ,"", "", "2020", "", "", "")) +  # Display every 5th year
  labs(y = "Log of Average Sale Price", x = "Year",color = "Treatment") +
  geom_vline(xintercept = "2010", linetype = "dashed", color = "black", linewidth = 1) + 
  scale_color_discrete(labels = c("Control", "Treatment")) + 
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black"))


#Now we repeat with 3K
DID3k <- read_excel("data/DTC_DID3K.xlsx",sheet = "Multifam 00-23")
DID3k$SaleMonth <- (((DID3k$SaleYear-2000)*12)+DID3k$MonthByYear)
DID3k$SaleMonthP <- (((DID3k$SaleYear-2000)*12)+DID3k$MonthByYear-128)
DID3k <- DID3k[DID3k$SalePrice < 2500000 & DID3k$SalePrice >= 1, ]
DID3k$FinishArea[DID3k$FinishArea == 0] <- 449
DID3k$LnSalePrice <- log(DID3k$SalePrice + 1)
DID3k$PricePerSqrft <- (DID3k$SalePrice/(DID3k$FinishArea))
DID3k$LnPricePerSqrft <- log(DID3k$SalePrice/(DID3k$FinishArea))
DID3k <- DID3k[!is.na(DID3k$CoreBin) & !is.na(DID3k$Age) & !is.na(DID3k$FinishArea) & !is.na(DID3k$LnSalePrice) &  !is.na(DID3k$SalePrice),]

DID3k_avg <- DID3k %>%
  group_by(Year, CoreBin) %>%
  summarize(mean_LnSalePrice = mean(LnSalePrice, na.rm = TRUE))

# Plot the summarized data
DID3k_avg %>%
 ggplot(aes(x = Year, y = mean_LnSalePrice, group = CoreBin, color = as.factor(CoreBin))) +
  geom_line(linewidth = 1) +
  scale_y_continuous(limits = c(10, 15)) +
  scale_x_discrete("Year",labels=c("2000","", "", "", "" ,"2005", "", "" ,"", "", "2010", "" ,"", "" ,"" ,"2015" ,"" ,"" ,"", "", "2020", "", "", "")) +  # Display every 5th year
  labs(y = "Log of Average Sale Price", x = "Year",color = "Treatment") +
  geom_vline(xintercept = "2010", linetype = "dashed", color = "black", linewidth = 1) + 
  scale_color_discrete(labels = c("Control", "Treatment")) +  
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black"))



#Now we repeat with 5K
DID5k <- read_excel("data/DTC_DID5k.xlsx",sheet = "Multifam 00-23")
DID5k <- DID5k[,1:25]
DID5k <- DID5k[DID5k$SalePrice < 2500000 & DID5k$SalePrice >= 1, ]
DID5k$FinishArea[DID5k$FinishArea == 0] <- 449
DID5k$LnSalePrice <- log(DID5k$SalePrice + 1)
DID5k$PricePerSqrft <- (DID5k$SalePrice/(DID5k$FinishArea))
DID5k$LnPricePerSqrft <- log(DID5k$SalePrice/(DID5k$FinishArea))
DID5k <- DID5k[!is.na(DID5k$CoreBin) & !is.na(DID5k$Age) & !is.na(DID5k$FinishArea) & !is.na(DID5k$LnSalePrice) &  !is.na(DID5k$SalePrice),]


DID5k_avg <- DID5k %>%
  group_by(Year, CoreBin) %>%
  summarize(mean_LnSalePrice = mean(LnSalePrice, na.rm = TRUE))

# Plot the summarized data
DID5k_avg %>%
 ggplot(aes(x = Year, y = mean_LnSalePrice, group = CoreBin, color = as.factor(CoreBin))) +
  geom_line(linewidth = 1) +
  scale_y_continuous(limits = c(10, 15)) +
  scale_x_discrete("Year",labels=c("2000","", "", "", "" ,"2005", "", "" ,"", "", "2010", "" ,"", "" ,"" ,"2015" ,"" ,"" ,"", "", "2020", "", "", "")) +  # Display every 5th year
  labs(y = "Log of Average Sale Price", x = "Year",color = "Treatment") +
  geom_vline(xintercept = "2010", linetype = "dashed", color = "black", linewidth = 1) + 
  scale_color_discrete(labels = c("Control", "Treatment")) +  
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black"))


#Now we repeat with 10K
DID10K <- read_excel("data/DTC_DID10k.xlsx",sheet = "Multifam 00-23")
DID10K <- DID10K[DID10K$SalePrice < 2500000 & DID10K$SalePrice >= 1, ]
DID10K$FinishArea[DID10K$FinishArea == 0] <- 449
DID10K$LnSalePrice <- log(DID10K$SalePrice + 1)
DID10K$PricePerSqrft <- (DID10K$SalePrice/(DID10K$FinishArea))
DID10K$LnPricePerSqrft <- log(DID10K$SalePrice/(DID10K$FinishArea))
DID10K <- DID10K[!is.na(DID10K$CoreBin) & !is.na(DID10K$Age) & !is.na(DID10K$FinishArea) & !is.na(DID10K$LnSalePrice) &  !is.na(DID10K$SalePrice),]  


# Plot the summarized data with custom legend
DID10k_avg <- DID10K %>%
  group_by(Year, CoreBin) %>%
  summarize(mean_LnSalePrice = mean(LnSalePrice, na.rm = TRUE))

# Plot the summarized data
DID10k_avg %>%
 ggplot(aes(x = Year, y = mean_LnSalePrice, group = CoreBin, color = as.factor(CoreBin))) +
  geom_line(linewidth = 1) +
  scale_y_continuous(limits = c(10, 15)) +
  scale_x_discrete("Year",labels=c("2000","", "", "", "" ,"2005", "", "" ,"", "", "2010", "" ,"", "" ,"" ,"2015" ,"" ,"" ,"", "", "2020", "", "", "")) +  # Display every 5th year
  labs(y = "Log of Average Sale Price", x = "Year",color = "Treatment") +
  geom_vline(xintercept = "2010", linetype = "dashed", color = "black", linewidth = 1) + 
  scale_color_discrete(labels = c("Control", "Treatment")) +  
  theme(panel.grid.major = element_blank(),panel.grid.minor = element_blank(),panel.background = element_blank(),axis.line = element_line(colour = "black"))
```




```{r}
#Difference-in-Differences LnSalePrice and LnSalePriceper sqr foot
#1k DID 
DID1k <- read_excel("data/DTC_DID1k.xlsx",sheet = "Multifam 00-23")
DID1k <- DID1k[,1:25]
DID1k <- DID1k[DID1k$SalePrice < 2500000 & DID1k$SalePrice >= 1, ]
DID1k$FinishArea[DID1k$FinishArea == 0] <- 449
DID1k$LnSalePrice <- log(DID1k$SalePrice + 1)
DID1k$PricePerSqrft <- (DID1k$SalePrice/(DID1k$FinishArea))
DID1k$LnPricePerSqrft <- log((DID1k$SalePrice/(DID1k$FinishArea)))
DID1k <- DID1k[!is.na(DID1k$CoreBin) & !is.na(DID1k$Age) & !is.na(DID1k$FinishArea) & !is.na(DID1k$LnSalePrice) &  !is.na(DID1k$SalePrice),]

DIDmodel1 <- lm(LnSalePrice ~ CoreBin*TimeBin + FinishArea + Age + factor(Tract) + factor(Year), data = DID1k)
DIDmodel1.1 <- lm(LnPricePerSqrft ~ CoreBin*TimeBin + Age + factor(Tract) + factor(Year), data = DID1k)


#3k DID 
DID3k <- read_excel("data/DTC_DID3k.xlsx",sheet = "Multifam 00-23")
DID3k <- DID3k[DID3k$SalePrice < 2500000 & DID3k$SalePrice >= 1, ]
DID3k$FinishArea[DID3k$FinishArea == 0] <- 449
DID3k$LnSalePrice <- log(DID3k$SalePrice + 1)
DID3k$PricePerSqrft <- (DID3k$SalePrice/(DID3k$FinishArea))
DID3k$LnPricePerSqrft <- log(DID3k$SalePrice/(DID3k$FinishArea))
DID3k <- DID3k[!is.na(DID3k$CoreBin) & !is.na(DID3k$Age) & !is.na(DID3k$FinishArea) & !is.na(DID3k$LnSalePrice) &  !is.na(DID3k$SalePrice),]

DIDmodel3 <- lm(LnSalePrice ~ CoreBin*TimeBin + FinishArea + Age + factor(Tract) + factor(Year), data = DID3k)
DIDmodel3.1 <- lm(LnPricePerSqrft ~ CoreBin*TimeBin + Age + factor(Tract) + factor(Year), data = DID3k)



#5k DID 
DID5k <- read_excel("data/DTC_DID5k.xlsx",sheet = "Multifam 00-23")
DID5k <- DID5k[,1:25]
DID5k <- DID5k[DID5k$SalePrice < 2500000 & DID5k$SalePrice >= 1, ]
DID5k$FinishArea[DID5k$FinishArea == 0] <- 449
DID5k$LnSalePrice <- log(DID5k$SalePrice + 1)
DID5k$PricePerSqrft <- (DID5k$SalePrice/(DID5k$FinishArea))
DID5k$LnPricePerSqrft <- log(DID5k$SalePrice/(DID5k$FinishArea))
DID5k <- DID5k[!is.na(DID5k$CoreBin) & !is.na(DID5k$Age) & !is.na(DID5k$FinishArea) & !is.na(DID5k$LnSalePrice) &  !is.na(DID5k$SalePrice),]

DIDmodel5 <- lm(log(SalePrice) ~ CoreBin * TimeBin + FinishArea + Age + factor(Tract) + factor(Year), data = DID5k)
DIDmodel5.1 <- lm(LnPricePerSqrft ~ CoreBin*TimeBin + Age + factor(Tract) + factor(Year), data = DID5k)


#10k DID 
DID10k <- read_excel("data/DTC_DID10k.xlsx",sheet = "Multifam 00-23")
DID10k <- DID10k[DID10k$SalePrice < 2500000 & DID10k$SalePrice >= 1, ]
DID10k$FinishArea[DID10k$FinishArea == 0] <- 449
DID10k$LnSalePrice <- log(DID10k$SalePrice + 1)
DID10k$PricePerSqrft <- (DID10k$SalePrice/(DID10k$FinishArea))
DID10k$LnPricePerSqrft <- log(DID10k$SalePrice/(DID10k$FinishArea))
DID10k <- DID10k[!is.na(DID10k$CoreBin) & !is.na(DID10k$Age) & !is.na(DID10k$FinishArea) & !is.na(DID10k$LnSalePrice) &  !is.na(DID10k$SalePrice),]


DIDmodel10 <- lm(log(SalePrice) ~ CoreBin * TimeBin + FinishArea + Age + factor(Tract) + factor(Year), data = DID10k)
DIDmodel10.1 <- lm(LnPricePerSqrft ~ CoreBin*TimeBin + Age + factor(Tract) + factor(Year), data = DID10k)


stargazer(DIDmodel1,DIDmodel3,DIDmodel5, DIDmodel10,type="text" )
stargazer(DIDmodel1.1,DIDmodel3.1,DIDmodel5.1, DIDmodel10.1,type="text" )
```




```{r}
#Matching Methods, as applied to post-treatment data 

DTC_DID_Full <- read_excel("data/DTC_DIDFULLCONTROL.xlsx", sheet = "Multifam 00-23")
DTC_DID_Full <- DTC_DID_Full[DTC_DID_Full$SalePrice < 2500000 & DTC_DID_Full$SalePrice >= 1, ]
# Filter rows where specified columns are not NA
DTC_DID_Full <- DTC_DID_Full[!is.na(DTC_DID_Full$CoreBin) & 
                             !is.na(DTC_DID_Full$Age) & 
                             !is.na(DTC_DID_Full$PrcntWhite) & 
                             !is.na(DTC_DID_Full$BAorHigher) & 
                             !is.na(DTC_DID_Full$BuildPreTrt), ]
DTC_DID_Full$FinishArea[DTC_DID_Full$FinishArea == 0] <- 449
DTC_DID_Full$LnSalePrice <- log(DTC_DID_Full$SalePrice + 1)
DTC_DID_Full$PricePerSqrft <- (DTC_DID_Full$SalePrice/(DTC_DID_Full$FinishArea))
DTC_DID_Full$LnPricePerSqrft <- log(DTC_DID_Full$SalePrice/(DTC_DID_Full$FinishArea))
DTC_DID_Full <- DTC_DID_Full[!is.na(DTC_DID_Full$CoreBin) & !is.na(DTC_DID_Full$Age) & !is.na(DTC_DID_Full$FinishArea) & !is.na(DTC_DID_Full$LnSalePrice) &  !is.na(DTC_DID_Full$SalePrice),]

DTC_DIDT1 <-  subset(DTC_DID_Full, TimeBin == 1)
DTC_DIDT0 <-  subset(DTC_DID_Full, TimeBin == 0)

ps<- glm(CoreBin ~  Age+ FinishArea+ PrcntWhite+ BAorHigher + BuildPreTrt, data=DTC_DIDT1, family =binomial())
summary(ps)

DTC_DIDT1$psvalue <- predict(ps, type = "response")

gps<- gbm(CoreBin ~  Age+ FinishArea+ PrcntWhite+ BAorHigher+ BuildPreTrt, distribution="bernoulli", data=DTC_DIDT1, n.trees=100, interaction.depth=4, train.fraction= 0.8, shrinkage=0.0005) 
summary(gps) 

DTC_DIDT1$gpsvalue <-  predict(gps, type = "response")

DTC_DIDT1$CoreBin <- as.factor(DTC_DIDT1$CoreBin)

# Fit a random forest model for propensity score estimation
rf_model <- randomForest(CoreBin ~ Age + FinishArea + PrcntWhite + BAorHigher + BuildPreTrt, 
                         data = DTC_DIDT1, 
                         ntree = 500,        # Number of trees
                         mtry = 3,           # Number of variables randomly sampled at each split
                         nodesize = 5)       # Minimum size of terminal nodes

# Predict propensity scores for the new dataset
DTC_DIDT1$rf_psvalue <- predict(rf_model, type = "prob")[,2]  # type = "prob" gives class probabilities

#using normal OLS after matching
DTC_DIDT1_Treat <- subset(DTC_DIDT1, CoreBin == 1)
DTC_DIDT1_Control <- subset(DTC_DIDT1, CoreBin == 0)

# No matching; constructing a pre-match matchit object
m.out0 <- matchit(CoreBin ~  Age+ FinishArea+ PrcntWhite+ BAorHigher + BuildPreTrt, data = DTC_DIDT1,
                 method = NULL, distance = "glm")
# Checking balance prior to matching
summary(m.out0)


psvalue_top <- DTC_DIDT1_Control[order(-DTC_DIDT1_Control$psvalue), ][1:10000, ]
psvalue_top <- rbind(psvalue_top, DTC_DIDT1_Treat)
m.out1 <- matchit(CoreBin ~  Age+ FinishArea+ PrcntWhite+ BAorHigher + BuildPreTrt, data = psvalue_top,
                 method = NULL, distance = "glm")
# Checking balance after to matching
summary(m.out1)

gpsvalue_top <- DTC_DIDT1_Control[order(-DTC_DIDT1_Control$gpsvalue), ][1:200, ]
gpsvalue_top<- rbind(gpsvalue_top, DTC_DIDT1_Treat)
m.out1 <- matchit(CoreBin ~  Age+ FinishArea+ PrcntWhite+ BAorHigher + BuildPreTrt, data = gpsvalue_top,
                 method = NULL, distance = "glm")
# Checking balance after to matching
summary(m.out1)


rf_psvalue_top <- DTC_DIDT1_Control[order(-DTC_DIDT1_Control$rf_psvalue), ][1:500, ]
rf_psvalue_top <- rbind(rf_psvalue_top, DTC_DIDT1_Treat)
m.out1 <- matchit(CoreBin ~  Age+ FinishArea+ PrcntWhite+ BAorHigher + BuildPreTrt, data = rf_psvalue_top,
                 method = NULL, distance = "glm")
# Checking balance after to matching
summary(m.out1)


#regressions with imporved sample selection
DIDmodelmps <- lm(log(SalePrice) ~ CoreBin + FinishArea + Age + factor(Tract) + factor(Year), data = psvalue_top)
DIDmodelmgps <- lm(log(SalePrice) ~ CoreBin + FinishArea + Age + factor(Tract) + factor(Year), data = gpsvalue_top)
DIDmodelmrf <- lm(log(SalePrice) ~ CoreBin + FinishArea + Age + factor(Tract) + factor(Year), data = rf_psvalue_top)


DIDmodelmps.1 <- lm(LnPricePerSqrft ~ CoreBin  + Age + factor(Tract) + factor(Year), data = psvalue_top)
DIDmodelmgps.1 <- lm(LnPricePerSqrft ~ CoreBin  + Age + factor(Tract) + factor(Year), data = gpsvalue_top)
DIDmodelmrf.1 <- lm(LnPricePerSqrft ~ CoreBin  + Age + factor(Tract) + factor(Year), data = rf_psvalue_top)

stargazer(DIDmodelmps,DIDmodelmgps,DIDmodelmrf,type ='text')
stargazer(DIDmodelmps.1,DIDmodelmgps.1,DIDmodelmrf.1,type ='text')


```




```{r}
#Quantile Difference-in-Differences

#Quantile DID 1 Km  
data1 <- read_excel("data/DTC_DID1K.xlsx",sheet = "Multifam 00-23")
data1 <- data.frame(data1)
data1<- data1[, 1:23]
data1$FinishArea[data1$FinishArea == 0] <- 449
data1$LnSalePrice <- log(data1$SalePrice + 1)
data1$PricePerSqrft <- (data1$SalePrice+1)/(data1$FinishArea)
data1$LnPricePerSqrft <- log(((data1$SalePrice+1)/(data1$FinishArea))+1)
data1 <- data1[!is.na(data1$CoreBin) & !is.na(data1$Age) & !is.na(data1$FinishArea) & !is.na(data1$LnSalePrice) &  !is.na(data1$SalePrice),]

QDID1 <- rq(LnSalePrice ~ CoreBin*TimeBin + Age + FinishArea+ factor(QuarterByYear), data=data1, tau=c(.25,.50,.75))

summary(QDID1)
QDID1plot <- summary(QDID1)
plot(QDID1plot)

QDID1.1 <- rq(LnPricePerSqrft ~ CoreBin*TimeBin + Age+ factor(QuarterByYear), data=data1, tau=c(.25,.50,.75))
summary(QDID1.1)
QDID1.1plot <- summary(QDID1.1)
plot(QDID1.1plot)

#Quantile DID 3 Km  
data3 <- read_excel("data/DTC_DID3K.xlsx",sheet = "Multifam 00-23")
data3 <- data.frame(data3)
data3<- data3[, 1:23]
data3$FinishArea[data3$FinishArea == 0] <- 449
data3$LnSalePrice <- log(data3$SalePrice + 1)
data3$PricePerSqrft <- (data3$SalePrice+1)/(data3$FinishArea)
data3$LnPricePerSqrft <- log(((data3$SalePrice+1)/(data3$FinishArea))+1)
data3 <- data3[!is.na(data3$CoreBin) & !is.na(data3$Age) & !is.na(data3$FinishArea) & !is.na(data3$LnSalePrice) &  !is.na(data3$SalePrice),]

QDID3 <- rq(LnSalePrice ~ CoreBin*TimeBin + Age + FinishArea+ factor(QuarterByYear), data=data3, tau=c(.25,.50,.75))
summary(QDID3)
QDID3plot <- summary(QDID3)
plot(QDID3plot)

QDID3.1 <- rq(LnPricePerSqrft ~ CoreBin*TimeBin + Age+ factor(QuarterByYear), data=data3, tau=c(.25,.50,.75))
summary(QDID3.1)
QDID3.1plot <- summary(QDID3.1)
plot(QDID3.1plot)


#Quantile DID 5 Km  
data5 <- read_excel("data/DTC_DID5K.xlsx",sheet = "Multifam 00-23")
data5 <- data.frame(data5)
data5<- data5[, 1:23]
data5$FinishArea[data5$FinishArea == 0] <- 449
data5$LnSalePrice <- log(data5$SalePrice + 1)
data5$PricePerSqrft <- (data5$SalePrice+1)/(data5$FinishArea)
data5$LnPricePerSqrft <- log(((data5$SalePrice+1)/(data5$FinishArea))+1)
data5 <- data5[!is.na(data5$CoreBin) & !is.na(data5$Age) & !is.na(data5$FinishArea) & !is.na(data5$LnSalePrice) &  !is.na(data5$SalePrice),]


QDID5 <- rq(LnSalePrice ~ CoreBin*TimeBin + Age + FinishArea+ factor(QuarterByYear), data=data5, tau=c(.25,.50,.75))
summary(QDID5)
QDID5plot <- summary(QDID5)
plot(QDID5plot)


QDID5.1 <- rq(LnPricePerSqrft ~ CoreBin*TimeBin + Age+ factor(QuarterByYear), data=data5, tau=c(.25,.50,.75))
summary(QDID5.1)
QDID5.1plot <- summary(QDID5.1)


#Quantile DID 10 Km  
data10 <- read_excel("data/DTC_DID10K.xlsx",sheet = "Multifam 00-23")
data10 <- data.frame(data10)
data10<- data10[, 1:23]
data10$FinishArea[data10$FinishArea == 0] <- 449
data10$LnSalePrice <- log(data10$SalePrice + 1)
data10$PricePerSqrft <- (data10$SalePrice+1)/(data10$FinishArea)
data10$LnPricePerSqrft <- log(((data10$SalePrice+1)/(data10$FinishArea))+1)
data10 <- data10[!is.na(data10$CoreBin) & !is.na(data10$Age) & !is.na(data10$FinishArea) & !is.na(data10$LnSalePrice) &  !is.na(data10$SalePrice),]

QDID10 <- rq(LnSalePrice ~ CoreBin*TimeBin + Age + FinishArea+ factor(QuarterByYear), data=data10, tau=c(.25,.50,.75))
summary(QDID10)
QDID10plot <- summary(QDID10)
plot(QDID10plot)


QDID10.1 <- rq(LnPricePerSqrft ~ CoreBin*TimeBin + Age+ factor(QuarterByYear), data=data10, tau=c(.25,.50,.75))
summary(QDID10.1)
QDID10.1plot <- summary(QDID10.1)
plot(QDID10.1plot)


```
